// Code generated by protoc-gen-go. DO NOT EDIT.
// source: math.proto

package mathproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlusRequest struct {
	A                    int64    `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlusRequest) Reset()         { *m = PlusRequest{} }
func (m *PlusRequest) String() string { return proto.CompactTextString(m) }
func (*PlusRequest) ProtoMessage()    {}
func (*PlusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_math_e0a6054131b3c1c6, []int{0}
}
func (m *PlusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlusRequest.Unmarshal(m, b)
}
func (m *PlusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlusRequest.Marshal(b, m, deterministic)
}
func (dst *PlusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlusRequest.Merge(dst, src)
}
func (m *PlusRequest) XXX_Size() int {
	return xxx_messageInfo_PlusRequest.Size(m)
}
func (m *PlusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlusRequest proto.InternalMessageInfo

func (m *PlusRequest) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *PlusRequest) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type PlusResponse struct {
	C                    int64    `protobuf:"varint,1,opt,name=C,proto3" json:"C,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlusResponse) Reset()         { *m = PlusResponse{} }
func (m *PlusResponse) String() string { return proto.CompactTextString(m) }
func (*PlusResponse) ProtoMessage()    {}
func (*PlusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_math_e0a6054131b3c1c6, []int{1}
}
func (m *PlusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlusResponse.Unmarshal(m, b)
}
func (m *PlusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlusResponse.Marshal(b, m, deterministic)
}
func (dst *PlusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlusResponse.Merge(dst, src)
}
func (m *PlusResponse) XXX_Size() int {
	return xxx_messageInfo_PlusResponse.Size(m)
}
func (m *PlusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlusResponse proto.InternalMessageInfo

func (m *PlusResponse) GetC() int64 {
	if m != nil {
		return m.C
	}
	return 0
}

func init() {
	proto.RegisterType((*PlusRequest)(nil), "mathproto.PlusRequest")
	proto.RegisterType((*PlusResponse)(nil), "mathproto.PlusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MathClient is the client API for Math service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathClient interface {
	Plus(ctx context.Context, in *PlusRequest, opts ...grpc.CallOption) (*PlusResponse, error)
}

type mathClient struct {
	cc *grpc.ClientConn
}

func NewMathClient(cc *grpc.ClientConn) MathClient {
	return &mathClient{cc}
}

func (c *mathClient) Plus(ctx context.Context, in *PlusRequest, opts ...grpc.CallOption) (*PlusResponse, error) {
	out := new(PlusResponse)
	err := c.cc.Invoke(ctx, "/mathproto.Math/Plus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServer is the server API for Math service.
type MathServer interface {
	Plus(context.Context, *PlusRequest) (*PlusResponse, error)
}

func RegisterMathServer(s *grpc.Server, srv MathServer) {
	s.RegisterService(&_Math_serviceDesc, srv)
}

func _Math_Plus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServer).Plus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mathproto.Math/Plus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServer).Plus(ctx, req.(*PlusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Math_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mathproto.Math",
	HandlerType: (*MathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plus",
			Handler:    _Math_Plus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}

func init() { proto.RegisterFile("math.proto", fileDescriptor_math_e0a6054131b3c1c6) }

var fileDescriptor_math_e0a6054131b3c1c6 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2c, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x25, 0x4d, 0x2e, 0xee,
	0x80, 0x9c, 0xd2, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x1e, 0x2e, 0x46, 0x47,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x46, 0x47, 0x10, 0xcf, 0x49, 0x82, 0x09, 0xc2, 0x73,
	0x52, 0x92, 0xe1, 0xe2, 0x81, 0x28, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x05, 0xc9, 0x3a, 0xc3,
	0xd4, 0x3a, 0x1b, 0x39, 0x72, 0xb1, 0xf8, 0x26, 0x96, 0x64, 0x08, 0x59, 0x72, 0xb1, 0x80, 0x54,
	0x09, 0x89, 0xe9, 0xc1, 0x2d, 0xd1, 0x43, 0xb2, 0x41, 0x4a, 0x1c, 0x43, 0x1c, 0x62, 0x9c, 0x12,
	0x43, 0x12, 0x1b, 0x58, 0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xe8, 0x3f, 0x3c, 0xab,
	0x00, 0x00, 0x00,
}
